import 'package:apoorva_app/model/organization/organization.dart';
import 'package:apoorva_app/model/organization/organization_snapshot.dart';
import 'package:apoorva_app/model/user/app_user.dart';
import 'package:apoorva_app/model/user/app_user_snapshot.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';

class UserService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<void> createIdentityAndProfile({
    required AppUser user,
    required String password,
  }) async {
    // 1. Initialize a secondary "Admin" app instance
    FirebaseApp secondaryApp = await Firebase.initializeApp(
      name: 'AdminApp',
      options: Firebase.app().options,
    );

    try {
      // 2. Create the user in Auth using the secondary app
      UserCredential credential = await FirebaseAuth.instanceFor(
        app: secondaryApp,
      ).createUserWithEmailAndPassword(email: user.email, password: password);

      // 3. CRITICAL: Use the UID generated by Auth for the Firestore Document
      final finalUser = AppUser(
        id: credential.user!.uid, // Link Auth UID to Firestore ID
        name: user.name,
        email: user.email,
        role: user.role,
        createdAt: DateTime.now(),
      );

      // 4. Save the profile to Firestore
      await _db.collection('users').doc(finalUser.id).set(finalUser.toJson());

      // 5. Cleanup the secondary app
      await secondaryApp.delete();
    } catch (e) {
      await secondaryApp.delete();
      throw Exception("Failed to create identity: $e");
    }
  }

  // Stream all users globally for the Master Admin
  Stream<List<AppUser>> getAllUsersGlobal() {
    return _db.collection('users').snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => AppUser.fromJson(doc.data())).toList();
    });
  }

  // Stream users for a specific shop
  Stream<List<AppUser>> getStaffForOrg(String orgId) {
    return _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .snapshots()
        .map(
          (snap) =>
              snap.docs.map((doc) => AppUser.fromJson(doc.data())).toList(),
        );
  }

  Future<void> saveUser(String orgId, AppUser user) async {
    await _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .doc(user.id)
        .set(user.toJson());
  }

  Future<void> deleteUser(String orgId, String userId) async {
    await _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .doc(userId)
        .delete();
  }

  Future<void> saveGlobalUser(AppUser user) async {
    // Writes directly to the root users collection
    await _db.collection('users').doc(user.id).set(user.toJson());
  }

  Future<void> mapUserToOrganization({
    required AppUser fullUser,
    required Organization fullOrg,
    String orgRole = 'staff', // You can pass 'manager' or 'admin' here
  }) async {
    final batch = _db.batch();

    // 1. Create the Slim User Snapshot for the Organization
    final userSnapshot = AppUserSnapshot(
      uid: fullUser.id,
      name: fullUser.name,
      email: fullUser.email,
      orgRole: orgRole,
    );

    // 2. Create the Slim Organization Snapshot for the User
    final orgSnapshot = OrganizationSnapshot(
      orgId: fullOrg.id,
      name: fullOrg.name,
      accentColor: fullOrg.accentColor,
    );

    // 3. Define the two paths
    final orgUserRef = _db
        .collection('organizations')
        .doc(fullOrg.id)
        .collection('users')
        .doc(fullUser.id);

    final userOrgRef = _db
        .collection('users')
        .doc(fullUser.id)
        .collection('organizations')
        .doc(fullOrg.id);

    // 4. Add both to the batch
    batch.set(orgUserRef, userSnapshot.toJson());
    batch.set(userOrgRef, orgSnapshot.toJson());

    // 5. Commit the transaction
    await batch.commit();
  }

  Future<void> unmapUserFromOrganization(String userId, String orgId) async {
    final batch = _db.batch();

    // Remove from Org sub-collection
    batch.delete(_db.doc('organizations/$orgId/users/$userId'));

    // Remove from User profile mappings
    batch.delete(_db.doc('users/$userId/organizations/$orgId'));

    await batch.commit();
  }

  Stream<List<OrganizationSnapshot>> getUserShops(String userId) {
    return _db
        .collection('users')
        .doc(userId)
        .collection('organizations')
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => OrganizationSnapshot.fromJson(doc.data()))
              .toList(),
        );
  }

  // Inside user_service.dart
  Stream<List<AppUserSnapshot>> getOrganizationUsers(String orgId) {
    return _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => AppUserSnapshot.fromJson(doc.data()))
              .toList(),
        );
  }
}
