import 'package:apoorva_app/model/organization/organization.dart';
import 'package:apoorva_app/model/organization/organization_snapshot.dart';
import 'package:apoorva_app/model/user/app_user.dart';
import 'package:apoorva_app/model/user/app_user_snapshot.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

class UserService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<AppUser> createIdentityAndProfile({
    required AppUser user,
    required String password,
  }) async {
    // 1. Initialize a secondary "Admin" app instance
    FirebaseApp secondaryApp = await Firebase.initializeApp(
      name: 'AdminApp',
      options: Firebase.app().options,
    );

    try {
      // 2. Create the user in Auth using the secondary app
      UserCredential credential = await FirebaseAuth.instanceFor(
        app: secondaryApp,
      ).createUserWithEmailAndPassword(email: user.email, password: password);

      // 3. CRITICAL: Use the UID generated by Auth for the Firestore Document
      final finalUser = AppUser(
        id: credential.user!.uid, // Link Auth UID to Firestore ID
        name: user.name,
        email: user.email,
        role: user.role,
        createdAt: DateTime.now(),
      );

      // 4. Save the profile to Firestore
      await _db.collection('users').doc(finalUser.id).set(finalUser.toJson());

      // 5. Cleanup the secondary app
      await secondaryApp.delete();
      return finalUser; // Return the complete user object with UID
    } catch (e) {
      await secondaryApp.delete();
      throw Exception("Failed to create identity: $e");
    }
  }

  // Stream all users globally for the Master Admin
  Stream<List<AppUser>> getAllUsersGlobal() {
    return _db.collection('users').snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => AppUser.fromJson(doc.data())).toList();
    });
  }

  // Stream users for a specific shop
  Stream<List<AppUser>> getStaffForOrg(String orgId) {
    return _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .snapshots()
        .map(
          (snap) =>
              snap.docs.map((doc) => AppUser.fromJson(doc.data())).toList(),
        );
  }

  Future<void> saveUser(String orgId, AppUser user) async {
    await _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .doc(user.id)
        .set(user.toJson());
  }

  Future<void> deleteUser(String orgId, String userId) async {
    await _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .doc(userId)
        .delete();
  }

  Future<void> saveGlobalUser(AppUser user) async {
    // Writes directly to the root users collection
    await _db.collection('users').doc(user.id).set(user.toJson());
  }

  Future<void> mapUserToOrganization({
    required AppUser fullUser,
    required Organization fullOrg,
    String orgRole = 'staff',
  }) async {
    final batch = _db.batch();

    // 1. Organization Snapshot (User document లో సేవ్ చేయడానికి)
    final orgSnapshot = OrganizationSnapshot(
      orgId: fullOrg.id,
      name: fullOrg.name,
      accentColor: fullOrg.accentColor,
    );

    // 2. User Snapshot (Organization సబ్-కలెక్షన్ లో సేవ్ చేయడానికి)
    final userSnapshot = AppUserSnapshot(
      uid: fullUser.id,
      name: fullUser.name,
      email: fullUser.email,
      orgRole: orgRole,
    );

    // 3. References
    // Path A: Organization లోపల ఉండే Staff list (Sub-collection)
    final orgUserRef = _db
        .collection('organizations')
        .doc(fullOrg.id)
        .collection('users')
        .doc(fullUser.id);

    // Path B: User document (Top-level document update)
    final userRef = _db.collection('users').doc(fullUser.id);

    // 4. Batch Operations
    // A: Organization సబ్-కలెక్షన్ లో యూజర్ ని యాడ్ చేస్తున్నాం
    batch.set(orgUserRef, userSnapshot.toJson());

    // B: User document లో ఉన్న 'assignedOrgs' array కి Snapshot ని యాడ్ చేస్తున్నాం
    batch.update(userRef, {
      'assignedOrgs': FieldValue.arrayUnion([orgSnapshot.toJson()]),
    });

    // 5. Commit
    await batch.commit();
  }

  Future<void> unmapUserFromOrganization({
    required String userId,
    required String orgId,
  }) async {
    // 1. ముందుగా యూజర్ డేటాను Fetch చేయాలి (Batch లో ఇది చేయలేము)
    final userRef = _db.collection('users').doc(userId);
    final doc = await userRef.get();

    if (!doc.exists) return;

    // 2. Dart లో లిస్ట్‌ని ఫిల్టర్ చేయాలి
    final userData = doc.data() as Map<String, dynamic>;
    final List assignedOrgs = userData['assignedOrgs'] ?? [];

    // ఆ orgId లేని మిగిలిన ఆర్గనైజేషన్లను మాత్రమే ఉంచండి
    final updatedOrgs = assignedOrgs
        .where((org) => org['orgId'] != orgId)
        .toList();

    // 3. ఇప్పుడు Batch ని స్టార్ట్ చేయండి
    final batch = _db.batch();

    // A: User document ని కొత్త లిస్ట్‌తో Update చేయండి
    batch.update(userRef, {'assignedOrgs': updatedOrgs});

    // B: Organization staff list నుండి యూజర్‌ని Delete చేయండి
    final orgUserRef = _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .doc(userId);
    batch.delete(orgUserRef);

    // 4. Commit the batch
    await batch.commit();
  }

  Stream<List<OrganizationSnapshot>> getUserShops(String userId) {
    return _db
        .collection('users')
        .doc(userId)
        .collection('organizations')
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => OrganizationSnapshot.fromJson(doc.data()))
              .toList(),
        );
  }

  // Inside user_service.dart
  Stream<List<AppUserSnapshot>> getOrganizationUsers(String orgId) {
    return _db
        .collection('organizations')
        .doc(orgId)
        .collection('users')
        .snapshots()
        .map(
          (snapshot) => snapshot.docs
              .map((doc) => AppUserSnapshot.fromJson(doc.data()))
              .toList(),
        );
  }

  // Inside your UserService class
  Future<AppUser?> getUserById(String uid) async {
    try {
      // 1. Reference the specific document in the 'users' collection
      final DocumentSnapshot doc = await _db.collection('users').doc(uid).get();

      // 2. Check if the document actually exists in Firestore
      if (doc.exists && doc.data() != null) {
        // 3. Convert the map data into your AppUser object
        // This assumes you have a fromJson or fromMap factory in your model
        return AppUser.fromJson(doc.data() as Map<String, dynamic>);
      } else {
        debugPrint("User document not found for UID: $uid");
        return null;
      }
    } catch (e) {
      debugPrint("Error fetching user data: $e");
      // You might want to rethrow or return null based on your error handling strategy
      return null;
    }
  }
}
