// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC8tk0hDmzdRpVFZoFwhKiiXCmuVhniR84",
    authDomain: "apoorva-debug-8f9eb.firebaseapp.com",
    projectId: "apoorva-debug-8f9eb",
    storageBucket: "apoorva-debug-8f9eb.firebasestorage.app",
    messagingSenderId: "719122164711",
    appId: "1:719122164711:web:575b976c3ab5ff119d6b42",
    measurementId: "G-95VVY2KCVZ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCihkwH4_3UbHSRNlQMeMno_1On85JynMk',
    appId: '1:942263598354:android:5fb76d6ff45387757247cb',
    messagingSenderId: '942263598354',
    projectId: 'apoorva-4ad68',
    storageBucket: 'apoorva-4ad68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfsMgLqnOpw1b9i6IeqRegA6II-W9MIKM',
    appId: '1:942263598354:ios:f893a97cdeef1f277247cb',
    messagingSenderId: '942263598354',
    projectId: 'apoorva-4ad68',
    storageBucket: 'apoorva-4ad68.firebasestorage.app',
    iosBundleId: 'com.example.apoorvaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfsMgLqnOpw1b9i6IeqRegA6II-W9MIKM',
    appId: '1:942263598354:ios:f893a97cdeef1f277247cb',
    messagingSenderId: '942263598354',
    projectId: 'apoorva-4ad68',
    storageBucket: 'apoorva-4ad68.firebasestorage.app',
    iosBundleId: 'com.example.apoorvaApp',
  );
}
