// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAKQD0i3HQ-7shjYpbfcwMmIeOmEYgZWsM",
    authDomain: "apoorva-production.firebaseapp.com",
    projectId: "apoorva-production",
    storageBucket: "apoorva-production.firebasestorage.app",
    messagingSenderId: "838267045796",
    appId: "1:838267045796:web:1a63c2153aa89f6d842331",
    measurementId: "G-H7NJ40NDN5",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4H-qYhakuccppfOS_OlNnVRMKGh-V9g',
    appId: '1:838267045796:android:8b3a9176f97991e5842331',
    messagingSenderId: '838267045796',
    projectId: 'apoorva-production',
    storageBucket: 'apoorva-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfsMgLqnOpw1b9i6IeqRegA6II-W9MIKM',
    appId: '1:838267045796:ios:8b3a9176f97991e5842331',
    messagingSenderId: '838267045796',
    projectId: 'apoorva-production',
    storageBucket: 'apoorva-production.firebasestorage.app',
    iosBundleId: 'com.example.apoorvaApp',
  );
}
