name: Flutter Test & Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
        #   flutter-version: '3.x.x' # Use your current version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests & Generate Coverage
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Get this from codecov.io
          files: coverage/lcov.info
        #   slug: nanirocks125/apoorva_app