name: Flutter Test & Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
        #   flutter-version: '3.x.x' # Use your current version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests & Generate Coverage
        run: flutter test --coverage

        # OPTIONAL: Clean the coverage report to exclude generated files
      # This ensures your 0.66% or 21% is based on your actual code.
      - name: Install LCOV
        run: sudo apt-get install -y lcov

      - name: Remove unwanted files from coverage
        run: |
          lcov --remove coverage/lcov.info 'lib/firebase_options*.dart' 'lib/**/*.g.dart' 'lib/**/*.freezed.dart' -o coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Get this from codecov.io
          files: coverage/lcov.info
        #   slug: nanirocks125/apoorva_app